version: '3'

services:
  app-node1:
    image: crate/fake-apache-log-generator
    volumes:
      - log-data:/out
    deploy:
      replicas: 3

  elasticsearch:
    image: elasticsearch:5
    networks: 
      - elk
    ports: 
      - 9200:9200
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      replicas: 1

  logstash:
    image: logstash:5
    networks: 
      - elk
    volumes:
      - ./logstash/docker-logstash.conf:/usr/share/logstash/config/logstash.conf
      - /var/lib/docker/volumes/elk_log-data/_data/:/applogs/
    command: -f /usr/share/logstash/config/logstash.conf
    depends_on:
      - elasticsearch
    deploy:
      replicas: 3

  kibana:
    image: kibana:5
    networks:
      - elk
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'
    deploy:
      replicas: 1

networks:
  elk:
    driver: "overlay"

volumes:
  esdata:
    driver: local
  log-data:
    driver: local